import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    authorBioContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 13,
        alignSelf: 'stretch',
    },
    profileNameUniContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: 2,
        flex: 1,
        flexGrow: 0,
        flexShrink: 0,
    },
    profileNameTwoIconsContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 5,
        flexDirection: 'row',
    },
    profileName: {
        color: 'var(--brand-black, #111)',
        leadingTrim: 'both',
        textEdge: 'cap',
        fontFamily: 'Poppins',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '600',
        // lineHeight: 'normal',
        lineHeight: 18,
    },
    verifiedIcon: {
        display: 'flex',
        width: 12,
        height: 12,
        padding: 4.444,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 2.222,
        borderRadius: 17.111,
        background: 'var(--brand-blue, #2656FF)',
    },
    uforaIcon: {
        display: 'flex',
        width: 12,
        height: 12,
        padding: 4.444,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 2.222,
        borderRadius: 17.111,
        background: 'var(--brand-black, #111)',
    },
    uniName:{
        // display: '-webkit-box',
        display: 'flex',
        WebkitBoxOrient: 'vertical',
        WebkitLineClamp: 1,
        alignSelf: 'stretch',
        overflow: 'hidden',
        color: 'var(--brand-grey, #4F4E4E)',
        leadingTrim: 'both',
        textEdge: 'cap',
        textOverflow: 'ellipsis',
        fontFamily: 'Poppins',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '400',
        // lineHeight: 'normal',
        lineHeight: 15,
    },
    profilePic: {
        width: 30,
        height: 30,
        borderRadius: 30,
        // background: 'url(<path-to-image>), lightgray 50% / cover no-repeat',
    },
});

