import { StyleSheet } from "react-native";

/***********************************Complete create or edit profile styles****************************************************** */
export const styles = StyleSheet.create({
  profilePicAndFormContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 25,
    marginTop: "30%",
  },
  profilePicContainer: {
    display: "flex",
    width: 104,
    height: 104,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    borderRadius: 157,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "#B8B8B8",
  },
  uploadPhotoText: {
    fontFamily: "Switzer",
    fontSize: 10,
    fontStyle: "normal",
    fontWeight: "500",
    color: "#B8B8B8",
  },
  titleAndFormContainer: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    gap: 15,
    justifyContent: "center",
  },
  formTitle: {
    marginBottom: 13,
    marginLeft: -190,
  },
  buttonContainer: {
    width: "90%",
    marginTop: 25,
  },
  // fieldContainer: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   backgroundColor: 'transparent',
  //   borderRadius: 20,
  //   padding: 2,
  //   marginTop: 8,
  // },
  iconAndTextInputContainer: {
    flexDirection: "row",
    height: 44.25,
    alignItems: "center",
    gap: 18,
    flexGrow: 1,
  },
  // introInputOuterContainer: {
  //   width: "90%",
  //   alignItems: 'flex-start',
  //   justifyContent: 'flex-start',
  //   borderColor: '#87929D',
  //   borderWidth: 1,
  //   borderRadius: 15,
  //   flexShrink: 0,
  //   flexGrow: 1,
  //   paddingLeft: 25,
  //   paddingRight: 15,
  //   paddingTop: 5,
  //   paddingBottom: 5,
  //   height: 107,
  //   position: 'relative',
  // },
  inputFieldOuterContainer: {
    width: "90%",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    borderColor: "#87929D",
    borderWidth: 1,
    borderRadius: 15,
    flexGrow: 1,
    paddingLeft: 25,
    paddingRight: 15,
    paddingTop: 5,
    paddingBottom: 5,
    position: "relative",
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2656FF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    width: "100%",
    height: 45,
    borderColor: "#2656FF",
    borderWidth: 1,
  },
  inputLabel: {
    position: "absolute",
    top: -8,
    left: 20,
    backgroundColor: "#FEFEFE",
    paddingHorizontal: 5,
    fontSize: 10,
    color: "#87929D",
  },
  // Remove below three later
  container: {
    alignItems: "center",
  },
  errorMessage: {
    marginTop: 5,
    marginBottom: 5,
    flexDirection: "row",
    marginLeft: -190,
  },
  // errorMessage: {
  //   color: '#CC3535',
  //   fontSize: 12,
  // },
  textInput: {
    width: "90%",
    flex: 1,
  },
});
