import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    postHeaderContainer: {
        display: 'flex',
        width: 373,
        justifyContent: 'space-between',
        alignItems: 'center',
        flexDirection: 'row',
    },
    profilePicNameUniTimeContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: 13,
        flexDirection: 'row',
    },
    profileNameUniTimeContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: 5,
    },
    profileNameTwoIconsContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
        flexDirection: 'row',
    },
    profileName: {
        color: 'var(--brand-black, #111)',
        leadingTrim: 'both',
        textEdge: 'cap',
        fontFamily: 'Poppins',
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: '600',
        // lineHeight: 'normal',
        lineHeight: 24,
    },
    verifiedAndUforaIconContainer: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 5,
        flexDirection: 'row',
    },
    verifiedIcon: {
        display: 'flex',
        width: 16,
        height: 16,
        padding: 4.444,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 2.222,
        borderRadius: 17.111,
        background: 'var(--brand-blue, #2656FF)',
    },
    uforaIcon: {
        display: 'flex',
        width: 16,
        height: 16,
        padding: 4.444,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 2.222,
        borderRadius: 17.111,
        background: 'var(--brand-black, #111)',
    },
    uniName:{
        color: 'var(--brand-grey, #4F4E4E)',
        leadingTrim: 'both',
        textEdge: 'cap',
        fontFamily: 'Poppins',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '400',
        // lineHeight: 'normal',
        lineHeight: 18,
    },
    timeAndGlobeIconContainer: {
        display: 'flex',
        alignItems: 'center',
        gap: 5,
        flexDirection: 'row',
    },
    time: {
        color: 'var(--form-field-outline, #87929D)',
        leadingTrim: 'both',
        textEdge: 'cap',
        fontFamily: 'Poppins',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '500',
        // lineHeight: 'normal',
        lineHeight: 15,
    },
    dotIcon: {
        width: 2,
        height: 2,
        fill: 'var(--form-field-outline, #87929D)',
    },
    globeIcon: {
        width: 10,
        height: 10,
    },
    profilePic: {
        width: 44,
        height: 44,
        borderRadius: 44,
        // background: "url(<path-to-image>), lightgray 50% / cover no-repeat",
    },
    moreIcon: {
        width: 24,
        height: 24,
        flexShrink: 0,
    },
});