import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  infoContainer: {
    display: "flex",
    width: 405,
    height: 140,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 15,
    flexShrink: 0,
    borderRadius: 15,
    backgroundColor: "var(--brand-white, #FEFEFE)",
  },
  imageNameContainer: {
    display: "flex",
    alignItems: "center",
    gap: 15,
  },
  profileName: {
    color: "var(--brand-black, #111)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Poppins",
    fontSize: 20,
    fontStyle: "normal",
    fontWeight: "600",
    lineHeight: 200,
  },
  uniName: {
    color: "var(--brand-grey, #4F4E4E)",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Poppins",
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "400",
    // lineHeight: "normal",
  },
  nameUniContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
  },
  statusContainer: {
    display: "flex",
    alignItems: "center",
    gap: 15,
  },
  individualStatusContainer:{
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  // statusCommon: {
  //   color: "#000",
  //   leadingTrim: "both",
  //   textEdge: "cap",
  //   fontFamily: "Poppins",
  //   fontStyle: "normal",
  //   // lineHeight: "normal",
  // },
  statusCount: {
    color: "#000",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Poppins",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "500",
    // lineHeight: "normal",
  },
  statusName: {
    color: "#000",
    leadingTrim: "both",
    textEdge: "cap",
    fontFamily: "Poppins",
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "400",
    // lineHeight: "normal",
    textTransform: "capitalize",
  },
  buttonContainer: {
    display: "flex",
    width: 282,
    alignItems: "flex-start",
    gap: 15,
  },
});